# Generated by Django 5.1.15 on 2026-08-24 05:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Lender",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=120, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="lenders/logos/"
                    ),
                ),
                ("website_url", models.URLField(blank=True)),
                ("active", models.BooleanField(default=True)),
                (
                    "priority",
                    models.IntegerField(
                        default=0,
                        help_text="Higher priority lenders are preferred as a tie-breaker in ranking.",
                    ),
                ),
            ],
            options={
                "ordering": ("-priority", "name"),
            },
        ),
        migrations.CreateModel(
            name="LenderProduct",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=120)),
                (
                    "product_type",
                    models.CharField(
                        choices=[
                            ("SHORT_TERM_LOAN", "Short Term Loan"),
                            ("CONSUMER_LOAN", "Consumer Loan"),
                            ("REFINANCING", "Refinancing"),
                            ("DEBT_CONSOLIDATION", "Debt Consolidation"),
                            ("CREDIT_CARD", "Credit Card"),
                            ("OTHER", "Other"),
                        ],
                        default="CONSUMER_LOAN",
                        max_length=32,
                    ),
                ),
                ("min_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("max_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("currency", models.CharField(default="BGN", max_length=3)),
                ("min_term_months", models.PositiveIntegerField()),
                ("max_term_months", models.PositiveIntegerField()),
                (
                    "min_income",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("application_url", models.URLField()),
                (
                    "tracking_type",
                    models.CharField(
                        choices=[
                            ("DIRECT", "Direct link"),
                            ("AFFILIATE", "Affiliate network"),
                            ("POSTBACK", "Server postback"),
                        ],
                        default="DIRECT",
                        max_length=16,
                    ),
                ),
                (
                    "tracking_url_template",
                    models.TextField(
                        blank=True,
                        help_text="Optional template for the outbound URL. Placeholders: {application_url}, {tracking_id}, {click_id}, {affiliate_id}.",
                    ),
                ),
                ("affiliate_id", models.CharField(blank=True, max_length=120)),
                (
                    "payout_model",
                    models.CharField(
                        choices=[
                            ("CPL", "Cost per lead"),
                            ("CPA", "Cost per action"),
                            ("CPS", "Cost per sale (fixed)"),
                            ("CPS_PERCENT", "Cost per sale (percentage)"),
                            ("HYBRID", "Hybrid"),
                        ],
                        default="CPL",
                        max_length=16,
                    ),
                ),
                (
                    "payout_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Fixed payout amount, or percentage (0-100) for CPS_PERCENT.",
                        max_digits=12,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                (
                    "lender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="lenders.lender",
                    ),
                ),
            ],
            options={
                "ordering": ("lender", "name"),
            },
        ),
        migrations.CreateModel(
            name="EligibilityRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "field",
                    models.CharField(
                        choices=[
                            ("requested_amount", "Requested Amount"),
                            ("requested_term_months", "Requested Term Months"),
                            ("monthly_income", "Monthly Income"),
                            ("employment_type", "Employment Type"),
                            ("employment_months", "Employment Months"),
                            ("existing_debt", "Existing Debt"),
                            ("monthly_debt_payment", "Monthly Debt Payment"),
                            ("loan_purpose", "Loan Purpose"),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "operator",
                    models.CharField(
                        choices=[
                            ("EQUALS", "Equals"),
                            ("NOT_EQUALS", "Not Equals"),
                            ("GREATER_THAN", "Greater Than"),
                            ("GREATER_THAN_OR_EQUAL", "Greater Than Or Equal"),
                            ("LESS_THAN", "Less Than"),
                            ("LESS_THAN_OR_EQUAL", "Less Than Or Equal"),
                            ("IN", "In"),
                            ("NOT_IN", "Not In"),
                            ("BETWEEN", "Between"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "value",
                    models.JSONField(
                        help_text="Scalar for comparisons; list for IN/NOT_IN; [low, high] for BETWEEN."
                    ),
                ),
                ("show_reason_to_customer", models.BooleanField(default=True)),
                (
                    "reason_template",
                    models.CharField(
                        blank=True,
                        help_text="Optional custom reason text shown when the rule passes.",
                        max_length=255,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="eligibility_rules",
                        to="lenders.lenderproduct",
                    ),
                ),
            ],
            options={
                "ordering": ("product", "field"),
            },
        ),
        migrations.AddConstraint(
            model_name="lenderproduct",
            constraint=models.UniqueConstraint(
                fields=("lender", "slug"), name="uniq_product_slug_per_lender"
            ),
        ),
    ]
