# Generated by Django 5.1.15 on 2026-08-25 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lenders", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lender",
            options={"ordering": ("display_order", "-priority", "name")},
        ),
        migrations.AddField(
            model_name="lender",
            name="display_order",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="lender",
            name="logo_url",
            field=models.URLField(blank=True),
        ),
    ]
