# Generated by Django 5.1.15 on 2026-08-25 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lenders", "0002_alter_lender_options_lender_display_order_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lenderproduct",
            options={"ordering": ("-priority", "lender", "name")},
        ),
        migrations.AddField(
            model_name="lenderproduct",
            name="priority",
            field=models.IntegerField(default=0),
        ),
    ]
