# Generated by Django 5.1.15 on 2026-08-28 06:23

from django.db import migrations, models


def backfill_status(apps, schema_editor):
    """Set the new lifecycle status from the existing ``active`` flag so no
    previously-inactive partner is silently reactivated by the ACTIVE default."""
    Lender = apps.get_model("lenders", "Lender")
    Lender.objects.filter(active=False).update(status="INACTIVE")
    Lender.objects.filter(active=True).update(status="ACTIVE")


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("lenders", "0003_alter_lenderproduct_options_lenderproduct_priority"),
    ]

    operations = [
        migrations.AddField(
            model_name="eligibilityrule",
            name="mandatory",
            field=models.BooleanField(
                default=False,
                help_text="If set, missing applicant data for this rule excludes the product; otherwise a missing value is reported as UNKNOWN, not a rejection.",
            ),
        ),
        migrations.AddField(
            model_name="lender",
            name="application_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="lender",
            name="contact_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="lender",
            name="contact_name",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="lender",
            name="display_name",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="lender",
            name="legal_name",
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name="lender",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="lender",
            name="partner_type",
            field=models.CharField(
                choices=[
                    ("LENDER", "Lender"),
                    ("BROKER", "Broker"),
                    ("OTHER", "Other"),
                ],
                default="LENDER",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="lender",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("ACTIVE", "Active"),
                    ("PAUSED", "Paused"),
                    ("INACTIVE", "Inactive"),
                ],
                db_index=True,
                default="ACTIVE",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="lenderproduct",
            name="max_age",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="lenderproduct",
            name="min_age",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="eligibilityrule",
            name="field",
            field=models.CharField(
                choices=[
                    ("requested_amount", "Requested Amount"),
                    ("requested_term_months", "Requested Term Months"),
                    ("monthly_income", "Monthly Income"),
                    ("employment_type", "Employment Type"),
                    ("employment_months", "Employment Months"),
                    ("existing_debt", "Existing Debt"),
                    ("monthly_debt_payment", "Monthly Debt Payment"),
                    ("loan_purpose", "Loan Purpose"),
                    ("age", "Age"),
                ],
                max_length=40,
            ),
        ),
        migrations.RunPython(backfill_status, noop_reverse),
    ]
