# Generated by Django 5.1.15 on 2026-08-28 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lenders", "0004_eligibilityrule_mandatory_lender_application_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lender",
            name="accepts_shared_leads",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="lender",
            name="delivery_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="lender",
            name="delivery_method",
            field=models.CharField(
                choices=[
                    ("MANUAL", "Manual / none (no automated delivery)"),
                    ("EMAIL", "Email"),
                    ("API", "Partner API"),
                    ("WEBHOOK", "Webhook"),
                ],
                default="MANUAL",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="lender",
            name="max_referrals_per_application",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="lender",
            name="minimum_match_score",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Overrides the global match threshold for this partner (0-100).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="lender",
            name="requires_user_selection",
            field=models.BooleanField(default=True),
        ),
    ]
