# Generated by Django 5.1.15 on 2026-08-31 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lenders", "0005_lender_accepts_shared_leads_lender_delivery_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lender",
            name="referral_allowed_fields",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="lender",
            name="referral_email_template",
            field=models.TextField(blank=True),
        ),
    ]
