# Generated by Django 5.1.15 on 2026-08-31 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lenders", "0006_lender_referral_allowed_fields_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lender",
            name="is_demo",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
