# Generated by Django 5.1.15 on 2026-09-02 16:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lenders", "0008_lenderproduct_ad_eligible"),
    ]

    operations = [
        migrations.AddField(
            model_name="lender",
            name="egn_required",
            field=models.BooleanField(
                default=False,
                help_text="If set, this partner requires the applicant's EGN to submit.",
            ),
        ),
        migrations.CreateModel(
            name="PartnerPrivacyProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("legal_name", models.CharField(blank=True, max_length=250)),
                ("trading_name", models.CharField(blank=True, max_length=200)),
                (
                    "company_registration_number",
                    models.CharField(blank=True, max_length=40),
                ),
                ("registered_address", models.CharField(blank=True, max_length=400)),
                ("privacy_url", models.URLField(blank=True)),
                (
                    "recipient_role",
                    models.CharField(
                        choices=[
                            ("CONTROLLER", "Independent controller"),
                            ("JOINT_CONTROLLER", "Joint controller"),
                            ("PROCESSOR", "Processor"),
                            ("UNKNOWN", "Not yet determined"),
                        ],
                        default="UNKNOWN",
                        max_length=20,
                    ),
                ),
                ("processing_purposes", models.JSONField(blank=True, default=list)),
                ("data_categories_shared", models.JSONField(blank=True, default=list)),
                ("egn_shared", models.BooleanField(default=False)),
                ("contact_information", models.CharField(blank=True, max_length=400)),
                ("active", models.BooleanField(default=False)),
                (
                    "partner_privacy_version",
                    models.CharField(default="1.0", max_length=40),
                ),
                (
                    "partner_privacy_last_updated",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "partner",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="privacy_profile",
                        to="lenders.lender",
                    ),
                ),
            ],
            options={
                "ordering": ("partner__display_order", "partner__name"),
            },
        ),
    ]
