# Generated by Django 5.1.15 on 2026-08-24 05:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("applications", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Consent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "consent_type",
                    models.CharField(
                        choices=[
                            ("PLATFORM_PROCESSING", "Platform processing"),
                            ("PARTNER_DATA_TRANSFER", "Partner data transfer"),
                            ("MARKETING", "Marketing"),
                        ],
                        max_length=32,
                    ),
                ),
                ("consent_text_version", models.CharField(max_length=40)),
                ("accepted", models.BooleanField(default=False)),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                ("privacy_policy_version", models.CharField(blank=True, max_length=40)),
                ("terms_version", models.CharField(blank=True, max_length=40)),
                ("ip_hash", models.CharField(blank=True, max_length=64)),
                ("user_agent_hash", models.CharField(blank=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consents",
                        to="applications.application",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("application", "consent_type"),
                        name="uniq_consent_per_type_per_application",
                    )
                ],
            },
        ),
    ]
