# Generated by Django 5.1.15 on 2026-09-02 16:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0004_applicantidentity"),
        ("consents", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConsentRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("applicant_ref", models.CharField(blank=True, max_length=64)),
                (
                    "consent_type",
                    models.CharField(
                        choices=[
                            ("PLATFORM_PROCESSING", "Platform processing"),
                            ("PARTNER_DATA_TRANSFER", "Partner data transfer"),
                            ("MARKETING", "Marketing"),
                        ],
                        max_length=32,
                    ),
                ),
                ("consent_version", models.CharField(blank=True, max_length=40)),
                ("privacy_notice_version", models.CharField(blank=True, max_length=40)),
                ("selected_partner_ids", models.JSONField(blank=True, default=list)),
                ("source", models.CharField(blank=True, max_length=120)),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("withdrawn_at", models.DateTimeField(blank=True, null=True)),
                ("ip_hash", models.CharField(blank=True, max_length=64)),
                ("user_agent_hash", models.CharField(blank=True, max_length=64)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consent_records",
                        to="applications.application",
                    ),
                ),
            ],
            options={
                "ordering": ("-timestamp",),
            },
        ),
    ]
