# Generated by Django 5.1.15 on 2026-08-24 05:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("actor_label", models.CharField(blank=True, max_length=100)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("APPLICATION_CREATED", "Application Created"),
                            ("APPLICATION_SUBMITTED", "Application Submitted"),
                            (
                                "APPLICATION_STATUS_CHANGED",
                                "Application Status Changed",
                            ),
                            ("CONSENT_ACCEPTED", "Consent Accepted"),
                            ("MATCH_CREATED", "Match Created"),
                            ("LEAD_ROUTED", "Lead Routed"),
                            ("LEAD_STATUS_CHANGED", "Lead Status Changed"),
                            ("COMMISSION_UPDATED", "Commission Updated"),
                            ("LENDER_UPDATED", "Lender Updated"),
                            ("PRODUCT_UPDATED", "Product Updated"),
                            ("RULE_UPDATED", "Rule Updated"),
                            ("WEBHOOK_RECEIVED", "Webhook Received"),
                            ("DATA_ANONYMIZED", "Data Anonymized"),
                        ],
                        max_length=64,
                    ),
                ),
                ("entity_type", models.CharField(max_length=64)),
                ("entity_id", models.CharField(blank=True, max_length=64)),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("ip_hash", models.CharField(blank=True, max_length=64)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-timestamp",),
                "indexes": [
                    models.Index(
                        fields=["entity_type", "entity_id"],
                        name="audit_audit_entity__9535bf_idx",
                    ),
                    models.Index(
                        fields=["action"], name="audit_audit_action_86e815_idx"
                    ),
                ],
            },
        ),
    ]
