# Generated by Django 5.1.15 on 2026-09-02 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("APPLICATION_CREATED", "Application Created"),
                    ("APPLICATION_SUBMITTED", "Application Submitted"),
                    ("APPLICATION_STATUS_CHANGED", "Application Status Changed"),
                    ("CONSENT_ACCEPTED", "Consent Accepted"),
                    ("MATCH_CREATED", "Match Created"),
                    ("LEAD_ROUTED", "Lead Routed"),
                    ("LEAD_STATUS_CHANGED", "Lead Status Changed"),
                    ("COMMISSION_UPDATED", "Commission Updated"),
                    ("LENDER_UPDATED", "Lender Updated"),
                    ("PRODUCT_UPDATED", "Product Updated"),
                    ("RULE_UPDATED", "Rule Updated"),
                    ("WEBHOOK_RECEIVED", "Webhook Received"),
                    ("DATA_ANONYMIZED", "Data Anonymized"),
                    ("EGN_COLLECTED", "Egn Collected"),
                    ("EGN_UPDATED", "Egn Updated"),
                    ("EGN_SUBMITTED_TO_PARTNER", "Egn Submitted To Partner"),
                    ("EGN_SUBMISSION_FAILED", "Egn Submission Failed"),
                    ("PARTNER_SUBMISSION_CREATED", "Partner Submission Created"),
                ],
                max_length=64,
            ),
        ),
    ]
