# Generated by Django 5.1.15 on 2026-08-24 05:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("applications", "0001_initial"),
        ("lenders", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Match",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("eligible", models.BooleanField(default=False)),
                ("score", models.PositiveIntegerField(default=0)),
                ("rank", models.PositiveIntegerField(blank=True, null=True)),
                ("reasons", models.JSONField(blank=True, default=list)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matches",
                        to="applications.application",
                    ),
                ),
                (
                    "lender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matches",
                        to="lenders.lender",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matches",
                        to="lenders.lenderproduct",
                    ),
                ),
            ],
            options={
                "ordering": ("application", "rank"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("application", "product"),
                        name="uniq_match_per_application_product",
                    )
                ],
            },
        ),
    ]
