# Generated by Django 5.1.15 on 2026-08-28 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matching", "0002_match_evaluation_match_reason_summary_match_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="referral_eligible",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="match",
            name="threshold_used",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
