# Generated by Django 5.1.15 on 2026-08-24 05:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "public_reference",
                    models.CharField(
                        db_index=True, editable=False, max_length=32, unique=True
                    ),
                ),
                (
                    "requested_amount",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("requested_currency", models.CharField(default="BGN", max_length=3)),
                ("requested_term_months", models.PositiveIntegerField()),
                (
                    "monthly_income",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("income_currency", models.CharField(default="BGN", max_length=3)),
                (
                    "employment_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("FULL_TIME", "Full Time"),
                            ("PART_TIME", "Part Time"),
                            ("SELF_EMPLOYED", "Self Employed"),
                            ("CONTRACT", "Contract"),
                            ("UNEMPLOYED", "Unemployed"),
                            ("RETIRED", "Retired"),
                            ("STUDENT", "Student"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "employment_months",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("has_existing_loans", models.BooleanField(default=False)),
                (
                    "existing_loan_balance",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "existing_monthly_payments",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "purpose",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("HOME_IMPROVEMENT", "Home Improvement"),
                            ("DEBT_CONSOLIDATION", "Debt Consolidation"),
                            ("VEHICLE", "Vehicle"),
                            ("MEDICAL", "Medical"),
                            ("EDUCATION", "Education"),
                            ("TRAVEL", "Travel"),
                            ("MAJOR_PURCHASE", "Major Purchase"),
                            ("EMERGENCY", "Emergency"),
                            ("OTHER", "Other"),
                        ],
                        max_length=32,
                    ),
                ),
                ("city", models.CharField(blank=True, max_length=120)),
                ("age_range", models.CharField(blank=True, max_length=16)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=32)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("STARTED", "Started"),
                            ("SUBMITTED", "Submitted"),
                            ("QUALIFIED", "Qualified"),
                            ("MATCHED", "Matched"),
                            ("ROUTED", "Routed"),
                            ("IN_PROGRESS", "In Progress"),
                            ("APPROVED", "Approved"),
                            ("FUNDED", "Funded"),
                            ("DECLINED", "Declined"),
                            ("EXPIRED", "Expired"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        max_length=16,
                    ),
                ),
                ("source", models.CharField(blank=True, max_length=120)),
                ("campaign", models.CharField(blank=True, max_length=120)),
                ("utm_source", models.CharField(blank=True, max_length=120)),
                ("utm_medium", models.CharField(blank=True, max_length=120)),
                ("utm_campaign", models.CharField(blank=True, max_length=120)),
                ("utm_term", models.CharField(blank=True, max_length=120)),
                ("utm_content", models.CharField(blank=True, max_length=120)),
                ("referrer", models.CharField(blank=True, max_length=500)),
                ("landing_page", models.CharField(blank=True, max_length=500)),
                ("ip_hash", models.CharField(blank=True, max_length=64)),
                ("user_agent_hash", models.CharField(blank=True, max_length=64)),
            ],
            options={
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["status", "created_at"],
                        name="application_status_413525_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="FinancialProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "monthly_income",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "income_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("SALARY", "Salary"),
                            ("PENSION", "Pension"),
                            ("BENEFITS", "Benefits"),
                            ("BUSINESS", "Business"),
                            ("OTHER", "Other"),
                        ],
                        max_length=16,
                    ),
                ),
                ("employment_type", models.CharField(blank=True, max_length=20)),
                (
                    "employment_duration",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "existing_debt",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "monthly_debt_payment",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "requested_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("requested_term", models.PositiveIntegerField(blank=True, null=True)),
                ("loan_purpose", models.CharField(blank=True, max_length=32)),
                (
                    "application",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="financial_profile",
                        to="applications.application",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
