# Generated by Django 5.1.15 on 2026-08-25 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="full_name",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
