# Generated by Django 5.1.15 on 2026-08-25 07:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0002_application_full_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Applicant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("first_name", models.CharField(blank=True, max_length=120)),
                ("last_name", models.CharField(blank=True, max_length=120)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=32)),
                (
                    "monthly_income_eur",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "employment_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("employed", "Employed"),
                            ("self_employed", "Self-employed"),
                            ("business_owner", "Business owner"),
                            ("pensioner", "Pensioner"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "existing_monthly_obligations_eur",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.AddField(
            model_name="application",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="application",
            name="current_step",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="application",
            name="public_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                editable=False,
                max_length=16,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="requested_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="requested_currency",
            field=models.CharField(default="EUR", max_length=3),
        ),
        migrations.AlterField(
            model_name="application",
            name="requested_term_months",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="application",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("STARTED", "Started"),
                    ("IN_PROGRESS", "In Progress"),
                    ("COMPLETED", "Completed"),
                    ("SUBMITTED", "Submitted"),
                    ("QUALIFIED", "Qualified"),
                    ("MATCHED", "Matched"),
                    ("PARTNER_SELECTED", "Partner Selected"),
                    ("ROUTED", "Routed"),
                    ("REFERRED", "Referred"),
                    ("PENDING", "Pending"),
                    ("APPROVED", "Approved"),
                    ("REJECTED", "Rejected"),
                    ("FUNDED", "Funded"),
                    ("DECLINED", "Declined"),
                    ("EXPIRED", "Expired"),
                    ("CANCELLED", "Cancelled"),
                ],
                db_index=True,
                default="DRAFT",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="applicant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="applications",
                to="applications.applicant",
            ),
        ),
        migrations.CreateModel(
            name="ApplicationEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("application_started", "Application Started"),
                            ("step_completed", "Step Completed"),
                            ("application_completed", "Application Completed"),
                            ("consent_granted", "Consent Granted"),
                            ("matching_started", "Matching Started"),
                            ("matching_completed", "Matching Completed"),
                            ("partner_viewed", "Partner Viewed"),
                            ("partner_selected", "Partner Selected"),
                            ("referral_created", "Referral Created"),
                            ("partner_status_updated", "Partner Status Updated"),
                        ],
                        db_index=True,
                        max_length=40,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="applications.application",
                    ),
                ),
            ],
            options={
                "ordering": ("timestamp",),
                "indexes": [
                    models.Index(
                        fields=["application", "event_type"],
                        name="application_applica_41f452_idx",
                    )
                ],
            },
        ),
    ]
