# Generated by Django 5.1.15 on 2026-09-02 16:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0003_applicant_application_completed_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApplicantIdentity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("egn_encrypted", models.TextField(blank=True, default="")),
                ("egn_last4", models.CharField(blank=True, default="", max_length=4)),
                ("egn_verified", models.BooleanField(default=False)),
                ("egn_collected_at", models.DateTimeField(blank=True, null=True)),
                (
                    "application",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="identity",
                        to="applications.application",
                    ),
                ),
            ],
            options={
                "verbose_name": "applicant identity",
                "verbose_name_plural": "applicant identities",
            },
        ),
    ]
