# Generated by Django 5.1.15 on 2026-08-24 05:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("applications", "0001_initial"),
        ("lenders", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("CREATED", "Created"),
                            ("SENT", "Sent"),
                            ("CLICKED", "Clicked"),
                            ("APPLICATION_STARTED", "Application Started"),
                            ("APPLICATION_COMPLETED", "Application Completed"),
                            ("APPROVED", "Approved"),
                            ("FUNDED", "Funded"),
                            ("DECLINED", "Declined"),
                            ("REJECTED", "Rejected"),
                            ("EXPIRED", "Expired"),
                        ],
                        db_index=True,
                        default="CREATED",
                        max_length=24,
                    ),
                ),
                ("external_lead_id", models.CharField(blank=True, max_length=120)),
                (
                    "external_application_id",
                    models.CharField(blank=True, max_length=120),
                ),
                (
                    "tracking_id",
                    models.CharField(editable=False, max_length=64, unique=True),
                ),
                ("click_id", models.CharField(blank=True, max_length=120)),
                ("affiliate_id", models.CharField(blank=True, max_length=120)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leads",
                        to="applications.application",
                    ),
                ),
                (
                    "lender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="leads",
                        to="lenders.lender",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="leads",
                        to="lenders.lenderproduct",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="LeadEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("CLICK", "Click"),
                            ("REDIRECT", "Redirect"),
                            ("APPLICATION_STARTED", "Application Started"),
                            ("APPLICATION_COMPLETED", "Application Completed"),
                            ("APPROVED", "Approved"),
                            ("DECLINED", "Declined"),
                            ("FUNDED", "Funded"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        max_length=32,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("external_event_id", models.CharField(blank=True, max_length=160)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="leads.lead",
                    ),
                ),
            ],
            options={
                "ordering": ("-timestamp",),
            },
        ),
        migrations.AddConstraint(
            model_name="lead",
            constraint=models.UniqueConstraint(
                fields=("application", "product"),
                name="uniq_lead_per_application_product",
            ),
        ),
        migrations.AddConstraint(
            model_name="leadevent",
            constraint=models.UniqueConstraint(
                condition=models.Q(("external_event_id__gt", "")),
                fields=("lead", "external_event_id"),
                name="uniq_external_event_per_lead",
            ),
        ),
    ]
