# Generated by Django 5.1.15 on 2026-08-25 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="external_reference",
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name="lead",
            name="partner_status",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="lead",
            name="referral_status",
            field=models.CharField(
                choices=[
                    ("selected", "Selected"),
                    ("referred", "Referred"),
                    ("received", "Received"),
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("funded", "Funded"),
                    ("failed", "Failed"),
                    ("unknown", "Unknown"),
                ],
                db_index=True,
                default="selected",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="referred_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="lead",
            name="selected_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
