# Generated by Django 5.1.15 on 2026-08-28 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0002_lead_external_reference_lead_partner_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lead",
            name="status",
            field=models.CharField(
                choices=[
                    ("CREATED", "Created"),
                    ("SENT", "Sent"),
                    ("CLICKED", "Clicked"),
                    ("APPLICATION_STARTED", "Application Started"),
                    ("APPLICATION_COMPLETED", "Application Completed"),
                    ("APPROVED", "Approved"),
                    ("FUNDED", "Funded"),
                    ("DECLINED", "Declined"),
                    ("REJECTED", "Rejected"),
                    ("CANCELLED", "Cancelled"),
                    ("EXPIRED", "Expired"),
                ],
                db_index=True,
                default="CREATED",
                max_length=24,
            ),
        ),
    ]
