# Generated by Django 5.1.15 on 2026-08-31 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0003_alter_lead_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="consent_version",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name="lead",
            name="match_score",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="lead",
            name="source",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="lead",
            name="utm_campaign",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="lead",
            name="utm_medium",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="lead",
            name="utm_source",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name="lead",
            name="referral_status",
            field=models.CharField(
                choices=[
                    ("matched", "Matched"),
                    ("selected", "Selected"),
                    ("sent", "Sent"),
                    ("opened", "Opened"),
                    ("started", "Started"),
                    ("completed", "Completed"),
                    ("approved", "Approved"),
                    ("funded", "Funded"),
                    ("rejected", "Rejected"),
                    ("expired", "Expired"),
                    ("referred", "Referred"),
                    ("received", "Received"),
                    ("pending", "Pending"),
                    ("failed", "Failed"),
                    ("unknown", "Unknown"),
                ],
                db_index=True,
                default="selected",
                max_length=16,
            ),
        ),
    ]
