# Generated by Django 5.1.15 on 2026-08-31 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0004_lead_consent_version_lead_match_score_lead_source_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="demo",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
