# Generated by Django 5.1.15 on 2026-09-02 16:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0004_applicantidentity"),
        ("leads", "0005_lead_demo"),
        ("lenders", "0009_lender_egn_required_partnerprivacyprofile"),
    ]

    operations = [
        migrations.CreateModel(
            name="PartnerSubmission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("SUBMITTED", "Submitted"),
                            ("ACCEPTED", "Accepted by partner"),
                            ("APPROVED", "Approved"),
                            ("FUNDED", "Funded"),
                            ("REJECTED", "Rejected"),
                            ("FAILED", "Submission failed"),
                            ("DEMO_SIMULATED", "Demo (simulated)"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "external_application_id",
                    models.CharField(blank=True, max_length=160),
                ),
                ("response_metadata", models.JSONField(blank=True, default=dict)),
                (
                    "funded_amount_eur",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("egn_included", models.BooleanField(default=False)),
                ("demo", models.BooleanField(db_index=True, default=False)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="partner_submissions",
                        to="applications.application",
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="partner_submissions",
                        to="leads.lead",
                    ),
                ),
                (
                    "lender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="partner_submissions",
                        to="lenders.lender",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="partner_submissions",
                        to="lenders.lenderproduct",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("application", "lender"),
                        name="uniq_submission_per_application_lender",
                    )
                ],
            },
        ),
    ]
